Tests
walt-id/waltid-nftkit pull request #48
Opened 2022-07-13 13:36 UTC by ahmedsmiai

@khemiriwalid @philpotisk

2022-07-14 10:16 UTC, philpotisk commented on src/test/kotlin/id/walt/nftkit/erc721Features/Erc721StandardTest.kt
> +        result.transactionId shouldNotBe null
To check if an update has succeeded, there should be always a read-request to validate the data.

2022-07-14 10:18 UTC, philpotisk requested changes
There are several failing tests. please make sure that they run reliable.
![image](https://user-images.githubusercontent.com/55081379/178960374-6f201211-8b0d-43e1-862b-53bb597addc1.png)
Please go over the code and discuss each test-case with @khemiriwalid

2022-07-14 10:18 UTC, philpotisk commented on src/test/kotlin/id/walt/nftkit/erc721Features/Erc721StandardTest.kt
> +        val byteArray = Files.readAllBytes(Paths.get("C:\\Users\\ahmed\\Desktop\\sa7eHXGY_400x400.jpg"))
this should not be hardcoded

2022-07-18 09:58 UTC, khemiriwalid commented on src/test/kotlin/id/walt/nftkit/erc721Features/Erc721StandardTest.kt
> +        result shouldNotBe ""
You need to compare the return value from the "getNftMetadataUri" function  with the expected result.

2022-07-18 10:07 UTC, khemiriwalid commented on src/test/kotlin/id/walt/nftkit/erc721Features/Erc721StandardTest.kt
> +        result shouldNotBe ""
You need to compare the return value from the "ownerOf" function with the expected result.

2022-07-18 10:07 UTC, khemiriwalid commented on src/test/kotlin/id/walt/nftkit/erc721Features/Erc721StandardTest.kt
> +        result.name shouldNotBe ""
You need to compare the return value from the "getTokenCollectionInfo" function with the expected result.

2022-07-18 10:10 UTC, khemiriwalid commented on src/test/kotlin/id/walt/nftkit/erc721Features/Erc721StandardTest.kt
> +            "0xf277BE034881eE38A9b270E5b6C5c6f333Af2517" )
Put an account address in the second parameter of the "getAccountNFTsByAlchemy" function

2022-07-18 10:44 UTC, khemiriwalid commented on src/test/kotlin/id/walt/nftkit/erc721Features/Erc721StandardTest.kt
> +
We can call "getTokenCollectionInfo" function to check the name and symbol of the deployed smart contract

2022-07-18 11:20 UTC, khemiriwalid commented on src/test/kotlin/id/walt/nftkit/accessControl/EvmBasedAccessControl.kt
> +
Add new test case for "Renounce ownership".
1- Deploy new smart contract
2- Call the "renounceOwnership" function on that smart contract instance
3- Check the owner of the smart contract.

2022-07-18 11:22 UTC, khemiriwalid commented on src/test/kotlin/id/walt/nftkit/accessControl/EvmBasedAccessControl.kt
> +        has shouldBe true
Call the "hasRole" function to checkout if the account has the specified role

2022-07-20 14:20 UTC, khemiriwalid approved these changes

2022-07-20 14:20 UTC, merged

2022-07-20 14:33 UTC, philpotisk commented
nice one :+1: